### ISSUE TITLE
Panic on zero-length input

### ISSUE THREAD

**Issue by coder543** [shamaton/msgpack#24]
It seems like `msgpack.Unmarshal(data, &value)` panics if `data` is zero-length.

I would just expect to get an error back that the input isn't long enough, not a panic. I'm not sure if this was an intentional design choice or not, but for comparison, `json.Unmarshal` just [returns an error](https://play.golang.org/p/XsL4IDt4Nl8) in this case, not a panic.

I'm adding a check in my code to avoid calling `msgpack.Unmarshal` with a zero-length value now, so I can work around it in the mean time.

**Comment by shamaton** [comment]
Fix. https://github.com/shamaton/msgpack/commit/e325f82642d9d1c0f9b97492b5c81d8bd31de132
