### ISSUE TITLE
Structs with map[string] to nested structs showing only zero values after marshal and unmarshal

### ISSUE THREAD

**Issue by Jldevictoria** [shamaton/msgpack#35]
Hi @shamaton I have been enjoying the simplicity and functionality of this library and it has been a great fit for my projects.
I recently came across an issue which is possibly just user error (I was hoping this is allowed) but I wanted to reach out in case its a bug.

I have a large struct which contains many maps and slices, some of which are maps with value types that are nested structs.  Those structs only contain primitive types, meaning everything can theoretically be decomposed into primitive types and serialized, however I am seeing misbehavior on these nested structs.  When I print the struct instances before marshalling, everything looks perfectly correct.  Then I am using the msgpack.Marshal function to convert the struct instance into a slice of bytes which I am then writing to a file using a zstd Writer.  When I uncompress the file, unmarshal the data using msgpack.Unmarshal, and try to print the data structure I see all the keys deserializing correctly, but the values which are nested structs show all of their contents set to 0. Currently I am not suspecting the compression library to be the issue since I have tried many other compression algos.

I'll share some pseudo code here so you can get the idea, and maybe you have some advice for me.

```golang
type foo struct {
	size  int
	start float64
	stop  float64
	step  float64
}

type bar struct {
	num   int
	b0    []int
	b1    []int
	b2    []int
	low   []int
	high  []int
	name  string
	group string
}

type baz struct {
	Count  int
	Foos   map[string](foo)
	Bars   map[string](bar)
	Tests  []string
	Names  map[string](struct{})
	Sizes  map[string](int)
	Plugs  map[string]([]float32)
	Chunks map[string]([][]float32)
	Banks  map[string](map[string]([]byte))
	Stores map[string](map[string]([]byte))
}

func main {

	var myBaz baz

	// Populate a huge myBaz structure here ~10 GB

	fmt.Println(myBaz)

	d, err := msgpack.Marshal(myBaz)
	if err != nil {
		fmt.Println("Error trying to marshal archive file.")
		os.Exit(1)
	}
	fileName := "example.zst"
	f, err := os.Create(fileName)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	zstd.WithEncoderConcurrency(0)
	zstd.WithEncoderLevel(1)
	w, err := zstd.NewWriter(f)
	if err != nil {
		fmt.Println("Couldn't create zstd writer.")
		os.Exit(1)
	}
	w.Write(d)
	w.Close()
	fmt.Println("Wrote to", fileName)
	f.Close()

	// Come back in a different command line option to read in the file.

	f, err := os.Open(fileName)
	if err != nil {
		fmt.Println("Error opening archive file.")
		os.Exit(1)
	}
	zstd.WithDecoderConcurrency(0)
	r, err := zstd.NewReader(f)
	if err != nil {
		fmt.Println("Couldn't create zstd reader.")
		os.Exit(1)
	}
	var rawData []byte
	rawData, err = io.ReadAll(r)
	if err != nil {
		fmt.Println("Couldn't read all decompressed data into buffer.")
		os.Exit(1)
	}
	r.Close()
	var myNewBaz baz
	err = msgpack.Unmarshal(rawData, &myNewBaz)
	if err != nil {
		fmt.Println("Couldn't unmarshall data from archive file.")
		os.Exit(1)
	}
	f.Close()

	fmt.Println(myNewBaz)

}
```

In the example above after unmarshalling an instance of baz like "myNewBaz" I would be able to see all of the expected contents from every field exactly as they appeared before I marshalled the original struct **except for "Foos" and "Bars"** which again were the only fields which had a map of string to nested structs.

I'm curious if there is a way to address this without having to rewrite my code to use slices of strings or something to perform the purpose of the foo and bar structs above.  I also thought about unrolling the structs into a pile of maps inside baz, but it feels dirty so I'm hoping there is a better way.  (and I'm also hoping I don't need to do code generation since its new to me and I'm worried about complicating my code for others on my team)

Thanks in advance.

**Comment by sgreben** [comment]
Unexported fields aren't serialized - you need to rename them like this:

```
type foo struct {
	Size  int
	Start float64
	Stop  float64
	Step  float64
}

type bar struct {
	Num   int
	B0    []int
	B1    []int
	B2    []int
	Low   []int
	High  []int
	Name  string
	Group string
}
```

**Comment by Jldevictoria** [comment]
> Unexported fields aren't serialized - you need to rename them like this:

This did the trick!  (capitalized all my fields to make them exported)

Wonderful help @sgreben.  I appreciate it!
